// US States — data for programmatic physician loan landing pages

export interface StateData {
  slug: string;
  name: string;
  abbr: string;
  majorCities: string[];
  medicalSchools: string[];
  healthSystems: string[];
}

export const STATES: StateData[] = [
  { slug: "alabama", name: "Alabama", abbr: "AL", majorCities: ["Birmingham", "Huntsville", "Mobile"], medicalSchools: ["UAB School of Medicine", "University of South Alabama"], healthSystems: ["UAB Health System", "Huntsville Hospital"] },
  { slug: "alaska", name: "Alaska", abbr: "AK", majorCities: ["Anchorage", "Fairbanks", "Juneau"], medicalSchools: ["WWAMI School of Medical Education"], healthSystems: ["Providence Alaska Medical Center", "Alaska Native Medical Center"] },
  { slug: "arizona", name: "Arizona", abbr: "AZ", majorCities: ["Phoenix", "Scottsdale", "Tucson"], medicalSchools: ["University of Arizona College of Medicine", "Mayo Clinic Alix School of Medicine"], healthSystems: ["Banner Health", "Mayo Clinic Arizona", "HonorHealth"] },
  { slug: "arkansas", name: "Arkansas", abbr: "AR", majorCities: ["Little Rock", "Fayetteville", "Fort Smith"], medicalSchools: ["UAMS College of Medicine"], healthSystems: ["UAMS Medical Center", "Arkansas Children's Hospital"] },
  { slug: "california", name: "California", abbr: "CA", majorCities: ["Los Angeles", "San Francisco", "San Diego", "Sacramento"], medicalSchools: ["Stanford", "UCSF", "UCLA David Geffen", "USC Keck"], healthSystems: ["Kaiser Permanente", "Cedars-Sinai", "Sutter Health", "Stanford Health Care"] },
  { slug: "colorado", name: "Colorado", abbr: "CO", majorCities: ["Denver", "Colorado Springs", "Boulder"], medicalSchools: ["University of Colorado School of Medicine"], healthSystems: ["UCHealth", "SCL Health", "Centura Health"] },
  { slug: "connecticut", name: "Connecticut", abbr: "CT", majorCities: ["Hartford", "New Haven", "Stamford"], medicalSchools: ["Yale School of Medicine", "UConn School of Medicine"], healthSystems: ["Yale New Haven Health", "Hartford HealthCare"] },
  { slug: "delaware", name: "Delaware", abbr: "DE", majorCities: ["Wilmington", "Dover", "Newark"], medicalSchools: ["Sidney Kimmel Medical College (partnership)"], healthSystems: ["ChristianaCare", "Bayhealth"] },
  { slug: "florida", name: "Florida", abbr: "FL", majorCities: ["Miami", "Tampa", "Orlando", "Jacksonville"], medicalSchools: ["University of Miami Miller", "University of Florida", "USF Morsani", "Mayo Clinic Florida"], healthSystems: ["AdventHealth", "Baptist Health South Florida", "Mayo Clinic Jacksonville"] },
  { slug: "georgia", name: "Georgia", abbr: "GA", majorCities: ["Atlanta", "Augusta", "Savannah"], medicalSchools: ["Emory School of Medicine", "Medical College of Georgia"], healthSystems: ["Emory Healthcare", "Piedmont Healthcare", "WellStar Health System"] },
  { slug: "hawaii", name: "Hawaii", abbr: "HI", majorCities: ["Honolulu", "Hilo", "Kailua"], medicalSchools: ["John A. Burns School of Medicine"], healthSystems: ["Queen's Health Systems", "Hawaii Pacific Health"] },
  { slug: "idaho", name: "Idaho", abbr: "ID", majorCities: ["Boise", "Meridian", "Idaho Falls"], medicalSchools: ["Idaho College of Osteopathic Medicine"], healthSystems: ["St. Luke's Health System", "Saint Alphonsus Health System"] },
  { slug: "illinois", name: "Illinois", abbr: "IL", majorCities: ["Chicago", "Naperville", "Springfield"], medicalSchools: ["Northwestern Feinberg", "University of Chicago Pritzker", "Rush Medical College", "Loyola Stritch"], healthSystems: ["Northwestern Medicine", "Advocate Aurora Health", "Rush University Medical Center"] },
  { slug: "indiana", name: "Indiana", abbr: "IN", majorCities: ["Indianapolis", "Fort Wayne", "Bloomington"], medicalSchools: ["Indiana University School of Medicine"], healthSystems: ["IU Health", "Community Health Network", "Ascension St. Vincent"] },
  { slug: "iowa", name: "Iowa", abbr: "IA", majorCities: ["Des Moines", "Iowa City", "Cedar Rapids"], medicalSchools: ["University of Iowa Carver College of Medicine"], healthSystems: ["University of Iowa Hospitals", "UnityPoint Health", "MercyOne"] },
  { slug: "kansas", name: "Kansas", abbr: "KS", majorCities: ["Wichita", "Overland Park", "Kansas City"], medicalSchools: ["University of Kansas School of Medicine"], healthSystems: ["University of Kansas Health System", "Ascension Via Christi"] },
  { slug: "kentucky", name: "Kentucky", abbr: "KY", majorCities: ["Louisville", "Lexington", "Bowling Green"], medicalSchools: ["University of Louisville", "University of Kentucky College of Medicine"], healthSystems: ["Norton Healthcare", "UK HealthCare", "Baptist Health"] },
  { slug: "louisiana", name: "Louisiana", abbr: "LA", majorCities: ["New Orleans", "Baton Rouge", "Shreveport"], medicalSchools: ["Tulane School of Medicine", "LSU Health Sciences Center"], healthSystems: ["Ochsner Health", "LCMC Health", "Our Lady of the Lake"] },
  { slug: "maine", name: "Maine", abbr: "ME", majorCities: ["Portland", "Bangor", "Lewiston"], medicalSchools: ["Tufts University Maine Track"], healthSystems: ["MaineHealth", "Northern Light Health"] },
  { slug: "maryland", name: "Maryland", abbr: "MD", majorCities: ["Baltimore", "Bethesda", "Rockville"], medicalSchools: ["Johns Hopkins", "University of Maryland", "Uniformed Services University"], healthSystems: ["Johns Hopkins Health System", "MedStar Health", "University of Maryland Medical System"] },
  { slug: "massachusetts", name: "Massachusetts", abbr: "MA", majorCities: ["Boston", "Cambridge", "Worcester"], medicalSchools: ["Harvard Medical School", "Tufts University", "Boston University", "UMass Chan"], healthSystems: ["Mass General Brigham", "Beth Israel Lahey Health", "Baystate Health"] },
  { slug: "michigan", name: "Michigan", abbr: "MI", majorCities: ["Detroit", "Ann Arbor", "Grand Rapids"], medicalSchools: ["University of Michigan", "Wayne State", "Michigan State"], healthSystems: ["Michigan Medicine", "Beaumont Health", "Spectrum Health"] },
  { slug: "minnesota", name: "Minnesota", abbr: "MN", majorCities: ["Minneapolis", "Saint Paul", "Rochester"], medicalSchools: ["University of Minnesota", "Mayo Clinic Alix School of Medicine"], healthSystems: ["Mayo Clinic", "Allina Health", "Fairview Health Services"] },
  { slug: "mississippi", name: "Mississippi", abbr: "MS", majorCities: ["Jackson", "Gulfport", "Hattiesburg"], medicalSchools: ["University of Mississippi Medical Center"], healthSystems: ["UMMC", "Baptist Memorial Health Care", "Singing River Health System"] },
  { slug: "missouri", name: "Missouri", abbr: "MO", majorCities: ["St. Louis", "Kansas City", "Springfield"], medicalSchools: ["Washington University", "Saint Louis University", "University of Missouri"], healthSystems: ["BJC HealthCare", "SSM Health", "Mercy"] },
  { slug: "montana", name: "Montana", abbr: "MT", majorCities: ["Billings", "Missoula", "Great Falls"], medicalSchools: ["WWAMI at University of Montana"], healthSystems: ["Billings Clinic", "Providence St. Patrick Hospital"] },
  { slug: "nebraska", name: "Nebraska", abbr: "NE", majorCities: ["Omaha", "Lincoln", "Bellevue"], medicalSchools: ["UNMC College of Medicine", "Creighton University"], healthSystems: ["Nebraska Medicine", "CHI Health", "Bryan Health"] },
  { slug: "nevada", name: "Nevada", abbr: "NV", majorCities: ["Las Vegas", "Reno", "Henderson"], medicalSchools: ["Kirk Kerkorian School of Medicine at UNLV", "UNR Med"], healthSystems: ["Renown Health", "Sunrise Health System"] },
  { slug: "new-hampshire", name: "New Hampshire", abbr: "NH", majorCities: ["Manchester", "Nashua", "Concord"], medicalSchools: ["Geisel School of Medicine at Dartmouth"], healthSystems: ["Dartmouth-Hitchcock Medical Center", "Elliot Health System"] },
  { slug: "new-jersey", name: "New Jersey", abbr: "NJ", majorCities: ["Newark", "Jersey City", "Princeton", "Morristown", "Chatham"], medicalSchools: ["Rutgers Robert Wood Johnson", "Rutgers New Jersey Medical School", "Hackensack Meridian School of Medicine"], healthSystems: ["RWJBarnabas Health", "Hackensack Meridian Health", "Atlantic Health System", "Virtua Health"] },
  { slug: "new-mexico", name: "New Mexico", abbr: "NM", majorCities: ["Albuquerque", "Santa Fe", "Las Cruces"], medicalSchools: ["University of New Mexico School of Medicine"], healthSystems: ["UNM Health", "Presbyterian Healthcare Services"] },
  { slug: "new-york", name: "New York", abbr: "NY", majorCities: ["New York City", "Buffalo", "Rochester", "Albany"], medicalSchools: ["Columbia", "Cornell Weill", "NYU Grossman", "Mount Sinai", "Albert Einstein"], healthSystems: ["NYU Langone", "NewYork-Presbyterian", "Northwell Health", "Mount Sinai Health System"] },
  { slug: "north-carolina", name: "North Carolina", abbr: "NC", majorCities: ["Charlotte", "Raleigh", "Durham"], medicalSchools: ["Duke University", "UNC School of Medicine", "Wake Forest"], healthSystems: ["Duke Health", "UNC Health", "Atrium Health", "Novant Health"] },
  { slug: "north-dakota", name: "North Dakota", abbr: "ND", majorCities: ["Fargo", "Bismarck", "Grand Forks"], medicalSchools: ["University of North Dakota School of Medicine"], healthSystems: ["Sanford Health", "Altru Health System"] },
  { slug: "ohio", name: "Ohio", abbr: "OH", majorCities: ["Columbus", "Cleveland", "Cincinnati"], medicalSchools: ["Cleveland Clinic Lerner", "Ohio State University", "Case Western Reserve", "University of Cincinnati"], healthSystems: ["Cleveland Clinic", "Ohio State Wexner Medical Center", "UC Health"] },
  { slug: "oklahoma", name: "Oklahoma", abbr: "OK", majorCities: ["Oklahoma City", "Tulsa", "Norman"], medicalSchools: ["OU College of Medicine", "OSU College of Osteopathic Medicine"], healthSystems: ["INTEGRIS Health", "OU Health", "Saint Francis Health System"] },
  { slug: "oregon", name: "Oregon", abbr: "OR", majorCities: ["Portland", "Eugene", "Salem"], medicalSchools: ["Oregon Health & Science University"], healthSystems: ["OHSU Health", "Providence Health & Services", "Legacy Health"] },
  { slug: "pennsylvania", name: "Pennsylvania", abbr: "PA", majorCities: ["Philadelphia", "Pittsburgh", "Allentown"], medicalSchools: ["Perelman at Penn", "Jefferson", "Temple", "Pitt School of Medicine"], healthSystems: ["Penn Medicine", "UPMC", "Jefferson Health", "Geisinger"] },
  { slug: "rhode-island", name: "Rhode Island", abbr: "RI", majorCities: ["Providence", "Warwick", "Cranston"], medicalSchools: ["Warren Alpert Medical School at Brown"], healthSystems: ["Lifespan", "Care New England"] },
  { slug: "south-carolina", name: "South Carolina", abbr: "SC", majorCities: ["Charleston", "Columbia", "Greenville"], medicalSchools: ["Medical University of South Carolina", "University of South Carolina"], healthSystems: ["MUSC Health", "Prisma Health", "Roper St. Francis"] },
  { slug: "south-dakota", name: "South Dakota", abbr: "SD", majorCities: ["Sioux Falls", "Rapid City", "Aberdeen"], medicalSchools: ["USD Sanford School of Medicine"], healthSystems: ["Sanford Health", "Avera Health"] },
  { slug: "tennessee", name: "Tennessee", abbr: "TN", majorCities: ["Nashville", "Memphis", "Knoxville"], medicalSchools: ["Vanderbilt", "University of Tennessee", "Meharry Medical College"], healthSystems: ["Vanderbilt University Medical Center", "HCA Healthcare", "Methodist Le Bonheur"] },
  { slug: "texas", name: "Texas", abbr: "TX", majorCities: ["Houston", "Dallas", "Austin", "San Antonio"], medicalSchools: ["Baylor College of Medicine", "UT Southwestern", "UT Houston McGovern", "Dell Medical School"], healthSystems: ["Houston Methodist", "UT Southwestern Medical Center", "Baylor Scott & White Health", "MD Anderson"] },
  { slug: "utah", name: "Utah", abbr: "UT", majorCities: ["Salt Lake City", "Provo", "Ogden"], medicalSchools: ["University of Utah School of Medicine"], healthSystems: ["University of Utah Health", "Intermountain Health"] },
  { slug: "vermont", name: "Vermont", abbr: "VT", majorCities: ["Burlington", "Montpelier", "Rutland"], medicalSchools: ["Larner College of Medicine at UVM"], healthSystems: ["UVM Medical Center", "Dartmouth-Hitchcock (regional)"] },
  { slug: "virginia", name: "Virginia", abbr: "VA", majorCities: ["Richmond", "Virginia Beach", "Arlington"], medicalSchools: ["University of Virginia", "Virginia Commonwealth University", "Eastern Virginia Medical School"], healthSystems: ["UVA Health", "Inova Health System", "Sentara Healthcare"] },
  { slug: "washington", name: "Washington", abbr: "WA", majorCities: ["Seattle", "Tacoma", "Spokane"], medicalSchools: ["University of Washington School of Medicine"], healthSystems: ["UW Medicine", "Swedish Health Services", "Providence"] },
  { slug: "west-virginia", name: "West Virginia", abbr: "WV", majorCities: ["Charleston", "Huntington", "Morgantown"], medicalSchools: ["West Virginia University School of Medicine", "Marshall University Joan C. Edwards"], healthSystems: ["WVU Medicine", "Cabell Huntington Hospital"] },
  { slug: "wisconsin", name: "Wisconsin", abbr: "WI", majorCities: ["Milwaukee", "Madison", "Green Bay"], medicalSchools: ["Medical College of Wisconsin", "UW School of Medicine"], healthSystems: ["Froedtert & MCW", "UW Health", "Ascension Wisconsin"] },
  { slug: "wyoming", name: "Wyoming", abbr: "WY", majorCities: ["Cheyenne", "Casper", "Laramie"], medicalSchools: ["WWAMI at University of Wyoming"], healthSystems: ["Cheyenne Regional Medical Center", "Wyoming Medical Center"] },
];

export function getStateBySlug(slug: string): StateData | undefined {
  return STATES.find((s) => s.slug === slug);
}
